# This is a TOML configuration file for a blog

title = "Web Development Chronicles"
author = "Lewis Benson"
theme = "hexo-theme-material"

[metadata]
description = "This is my personal blog, where I write about web development and other topics."
tags = ["web development", "programming", "tech"]
keywords = ["web development", "JavaScript", "HTML", "CSS"]
language = "en"

[server]
port = 8080
baseurl = "https://www.example.com/blog"

date_format = "YYYY-MM-DD"

[disqus]
shortname = ""

[google_analytics]
tracking_id = "UA-123456-1"

[sitemap]
changefreq = "monthly"
priority = 0.5

[social]
twitter = "https://twitter.com/TM_LBenson"
github = "https://github.com/tm-LBenson"
linkedin = "https://www.linkedin.com/in/tm-lewis-benson/"


