# @format

# main menu navigation url and icon

menu:
  Index:
    url: /
    icon: fas fa-home
  Tags:
    url: /tags/coding/
    icon: fas fa-tags
  Categories:
    url: /categories/Code-Fellows
    icon: fas fa-bookmark
  Archives:
    url: /archives
    icon: fas fa-archive

time:
  enable: false
  year: 2019 #
  month: 06 #
  date: 28 #
  hour: 00 #
  minute: 00 #
  second: 00 #

cover:
  showPrevNext: true
  showIndicators: true
  autoLoop: true
  duration: 120
  intervalTime: 5000
  useConfig: false
  video:
    enable: false
    src:
      - https://txmov2.a.yximgs.com/upic/2021/04/09/22/BMjAyMTA0MDkyMjMwMDhfMTg1ODk2MDg4N180NzUyOTMyMjA4Nl8xXzM=_b_B8e080d7ede19e6674d48a9f12545007b.mp4?pkey=AAVAfNhi5_f-HGkIPXrY5w6nyf4JibwOY-WwdHgSJ2aSoi-2WQLpiYDunLbRZQuESz875eMdsepRlVFtXg9nuQY58uRc-7AsF0kEMNR6QYBj56g9JFFMSGdsoKK2-SV27u8&tag=1-1617978682-xpcwebprofile-0-lcvipceuti-9e40072f87531f1a&clientCacheKey=3xbbtbrfxqpccp4_b.mp4
      - https://txmov2.a.yximgs.com/upic/2021/04/09/21/BMjAyMTA0MDkyMTQyNDRfMTg1ODk2MDg4N180NzUyNjAyMzA0N18xXzM=_b_B83b004b85aba8eca3ded270637616575.mp4
      - https://txmov2.a.yximgs.com/upic/2021/04/09/21/BMjAyMTA0MDkyMTU4MDNfMTg1ODk2MDg4N180NzUyNzE0MzkyNV8xXzM=_b_Bf94cee6bd181efeaca64049bd2e4e276.mp4
# index page dream text,

# index page dream text,

dream:
  enable: true
  showTitle: true
  title: My Professional Vision
  text: My Professional Vision is to become a highly skilled and respected full-stack developer, known for my ability to deliver exceptional solutions for my clients. I am constantly seeking new opportunities to learn and grow, and I am committed to staying up-to-date on the latest technologies and best practices in the industry. As I continue to build my skills and knowledge, I am excited to work on meaningful projects that make a positive impact in the world.

music:
  enable: false
  title: #Non-bottom mode is valid
    enable: true
    show: Listen to music
  autoHide: true
  server: netease #require	music platform: netease, tencent, kugou, xiami, baidu
  type: playlist
  id: 503838841 #require	song id / playlist id / album id / search keyword
  fixed: true
  autoplay: false
  theme: '#42b983'
  loop: 'all'
  order: 'random'
  preload: 'auto'
  volume: 0.7
  listFolded: true
  hideLrc: true

musics:
  enable: false
  title:
    enable: true
    show: Music
  server: tencent
  type: playlist
  id: 1776127550
  fixed: false
  autoplay: true
  theme: '#42b983'
  loop: 'all'
  order: 'random'
  preload: 'auto'
  volume: 0.7
  listFolded: false
  listMaxHeight: '525px'

video:
  enable: false
  showTitle: true
  title: Video Title
  url:
  iframeUrl:
  pic:
  thumbnails:
  height:
  autoplay: false
  theme: '#42b983'
  loop: false
  preload: 'auto'
  volume: 0.7

recommend:
  enable: true
  showTitle: true
  useConfig: false

favicon: /favicon.png
logo: /medias/logo.png

indexbtn:
  enable: true
  name: Github
  icon: fab fa-github-alt
  url: https://github.com/tm-LBenson

socialLink:
  github: https://github.com/tm-LBenson
  email: tm-lewisbenson@gmail.com
  rss: false

toc:
  enable: true
  heading: h2, h3, h4
  collapseDepth: 0
  showToggleBtn: true

code:
  lang: true
  copy: true
  shrink: true
  break: false

reward:
  enable: true
  title: reward
  wechat: /medias/reward/wechat.png
  alipay: /medias/reward/alipay.jpg

copyright:
  enable: false
  minCharNumber: 120
  description: copyright description

mathjax:
  enable: false
  cdn: https://cdn.bootcss.com/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML

postInfo:
  date: true
  update: false
  wordCount: false
  totalCount: false
  min2read: false
  readCount: false

clicklove:
  enable: true

sakura:
  enable: false

mouseStar:
  enable: false

snowdown:
  enable: false

# profile in about page, including avatars, career, and personal introductions.

profile:
  avatar: /medias/avatar.jpg
  career: Software Engineer
  introduction: If you wish to succeed, you should use persistence as your good friend, experience as your reference, prudence as your brother and hope as your sentry.

# config my projects informations in about page.
# If you don't want to display this `My Projects` content, you can deactivate or delete this configuration.

myProjects:
  enable: true
  data:
    hexo-theme-matery:
      icon: fas fa-file-alt
      iconBackground: 'linear-gradient(to bottom right, #66BB6A 0%, #81C784 100%)'
      url: https://github.com/tm-LBenson
      desc: I will need to include a project here
    Fenix:
      icon: fas fa-database
      iconBackground: 'linear-gradient(to bottom right, #F06292 0%, #EF5350 100%)'
      url: https://github.com/tm-LBenson
      desc: I will need to include a project here
    typora-vue-theme:
      icon: fas fa-file-alt
      iconBackground: 'linear-gradient(to bottom right, #29B6F6 0%, #1E88E5 100%)'
      url: https://github.com/tm-LBenson
      desc: I will need to include a project here

# config my skills informations in about page.
# If you don't want to display this `My Skills` content, you can deactivate or delete this configuration.

mySkills:
  enable: true
  data:
    JavaScript:
      background: 'linear-gradient(to right, #9900FF 0%, #CC66FF 100%)'
      percent: 80%
    HTML5:
      background: 'linear-gradient(to right, #2196F3 0%, #42A5F5 100%)'
      percent: 80%
    CSS:
      background: 'linear-gradient(to right, #00BCD4 0%, #80DEEA 100%)'
      percent: 70%
    SQL:
      background: 'linear-gradient(to right, #4CAF50 0%, #81C784 100%)'
      percent: 90%

# config gallery of my photos in about page.
# If you don't want to display this `Gallery` content, you can deactivate or delete this configuration.

myGallery:
  enable: true
  data:
    - /medias/featureimages/0.jpg
    - /medias/featureimages/1.jpg
    - /medias/featureimages/2.jpg

# Whether to display post-calender in the `archive` page

postCalendar: true

gitalk:
  enable: true
  owner: tm-LBenson
  repo: https://github.com/tm-LBenson/
  oauth:
    clientId: 8735393a1fc8fd974cf3
    clientSecret: ${{ process.env.GITALK_CLIENT_SECRET}}
  admin: tm-LBenson

gitment:
  enable: false
  owner:
  repo:
  oauth:
    clientId:
    clientSecret:

disqus:
  enable: false
  shortname: tmlbenson

livere:
  enable: false
  uid:

tcaptcha:
  enable: true
  appid: xxxxxxxxxx # 你的appid

# The configuration of the Valine comment module is not activated by default.
# To use it, activate the configuration item and set appId and appKey.

valine:
  enable: false
  appId: #
  appKey: #
  serverURLs: #
  notify: false
  verify: false
  visitor: true
  avatar: 'mm' #
  pageSize: 10
  placeholder: 'just go go' # Comment Box placeholder
  background: /medias/comment_bg.png
  coolpushkey:

waline:
  enable: false

  serverURL: https://waline.your-domain.com
  avatar: 'mp'

changyan:
  enable: false
  appId:
  conf:

githubLink:
  enable: true
  url: https://github.com/tm-LBenson
  title: GitHub

twikoo:
  enable: false
  envId: twikoo-1gs9l0fb17e7897a

verifyPassword:
  enable: false
  promptMessage: Password is required
  errorMessage: Incorrect password!

busuanziStatistics:
  enable: true
  totalTraffic: true
  totalNumberOfvisitors: true

googleAnalytics:
  enable: false
  id:

baiduAnalytics:
  enable: false
  id:

baiduPush: true

libs:
  css:
    matery: /css/matery.css
    mycss: /css/my.css
    post: /css/post.css
    reward: /css/reward.css
    dark: /css/dark.css
    indexcover: /css/indexcover.css
    gallery: /css/gallery.css
    fontAwesome: /libs/awesome/css/all.min.css # V6.1.2 20220809
    materialize: /libs/materialize/materialize.min.css # 1.0.0 20211109
    aos: /libs/aos/aos.css
    animate: /libs/animate/animate.min.css # V3.5.1
    lightgallery: /libs/lightGallery/css/lightgallery.min.css # V1.10.0
    aplayer: /libs/aplayer/APlayer.min.css
    dplayer: /libs/dplayer/DPlayer.min.css
    gitalk: /libs/gitalk/gitalk.css
    jqcloud: /libs/jqcloud/jqcloud.css
    tocbot: /libs/tocbot/tocbot.css
    prism: /libs/prism/prism.min.css
    mermaid: /libs/mermaid/mermaid.min.css
    fancybox: /libs/fancybox/jquery.fancybox.css
    justifiedGallery: /libs/justifiedGallery/justifiedGallery.min.css
  js:
    matery: /js/matery.js
    sc2tc: /js/tw_cn.js
    jquery: /libs/jquery/jquery-3.6.0.min.js #3.6.0 20211109
    materialize: /libs/materialize/materialize.min.js # 1.0.0
    masonry: /libs/masonry/masonry.pkgd.min.js # v4.0.0
    aos: /libs/aos/aos.js
    scrollProgress: /libs/scrollprogress/scrollProgress.min.js
    lightgallery: /libs/lightGallery/js/lightgallery-all.min.js # V1.10.0
    typed: /libs/typed/typed.js
    clicklove: /libs/others/clicklove.js
    sakura: /libs/others/sakura.js
    star: /libs/others/star.js
    snow: /libs/others/snow.js
    tcaptcha: /libs/others/TencentCaptcha.js
    busuanzi: /libs/others/busuanzi.pure.mini.js
    aplayer: /libs/aplayer/APlayer.min.js
    meting: /libs/aplayer/Meting.min.js
    dplayer: /libs/dplayer/DPlayer.min.js
    crypto: /libs/cryptojs/crypto-js.min.js
    echarts: /libs/echarts/echarts.min.js
    gitalk: /libs/gitalk/gitalk.min.js
    valine: /libs/valine/Valine.min.js
    minivaline: /libs/minivaline/MiniValine.js # latest
    waline: /libs/waline/Waline.min.js
    twikoo: /libs/twikoo/twikoo.all.min.js
    jqcloud: /libs/jqcloud/jqcloud-1.0.4.min.js
    tocbot: /libs/tocbot/tocbot.min.js
    canvas_nest: /libs/background/canvas-nest.js
    ribbon: /libs/background/ribbon.min.js
    ribbonRefresh: /libs/background/ribbon-refresh.min.js
    ribbon_dynamic: /libs/background/ribbon-dynamic.js
    instantpage: /libs/instantpage/instantpage.js
    mermaid: /libs/mermaid/mermaid.min.js
    fancybox: /libs/fancybox/fancybox.js
    justifiedGallery: /libs/justifiedGallery/justifiedGallery.min.js
    prism: /libs/prism/prism.min.js
    codeblock: /libs/codeBlock/codeBlockFuction.js
    codelang: /libs/codeBlock/codeLang.js
    codecopy: /libs/codeBlock/codeCopy.js
    codeshrink: /libs/codeBlock/codeShrink.js

# The post featured images that needs to be displayed when there is no image.

featureImages:
  - /medias/featureimages/0.jpg
  - /medias/featureimages/1.jpg
  - /medias/featureimages/2.jpg
  - /medias/featureimages/3.jpg
  - /medias/featureimages/4.jpg
  - /medias/featureimages/5.jpg
  - /medias/featureimages/6.jpg
  - /medias/featureimages/7.jpg
  - /medias/featureimages/8.jpg
  - /medias/featureimages/9.jpg
  - /medias/featureimages/10.jpg
  - /medias/featureimages/11.jpg
  - /medias/featureimages/12.jpg
  - /medias/featureimages/13.jpg
  - /medias/featureimages/14.jpg
  - /medias/featureimages/15.jpg
  - /medias/featureimages/16.jpg
  - /medias/featureimages/17.jpg
  - /medias/featureimages/18.jpg
  - /medias/featureimages/19.jpg
  - /medias/featureimages/20.jpg
  - /medias/featureimages/21.jpg
  - /medias/featureimages/22.jpg
  - /medias/featureimages/23.jpg

reprint:
  enable: true # whether enable reprint section 是否启用“转载规则限定模块”
  default: cc_by

# DaoVoice online contact
daovoice:
  enable: false
  app_id:

# Tidio online contact
tidio:
  enable: false
  public_key:

tuxiaochao:
  enable: false
  productId:

canvas_nest:
  enable: false
  color: 0,0,255
  pointColor: 0,0,255
  opacity: 0.7
  zIndex: -1
  count: 99

ribbon:
  enable: false
  size: 150
  alpha: 0.6
  zIndex: -1
  clickChange: false

ribbon_dynamic:
  enable: false

sharejs:
  enable: true
  sites: twitter,facebook,linkedin

addthis:
  enable: false
  pubid:

subtitle:
  enable: true
  loop: true
  showCursor: true
  startDelay: 1000
  typeSpeed: 50
  backSpeed: 10
  sub:
    - Full-stack developer with a passion for innovation

    - Strong expertise in the MERN stack

    - Stay up-to-date on the latest tech industry developments

    - Enjoy building computers as a hobby

    - Believe in the power of technology and continuous learning

navMenu:
  mleft: false
  bgColor: ' '

instantpage:
  enable: true

banner:
  enable: true

translate:
  enable: false

icp:
  enable: false
  url:
  text:

jsDelivr:
  url:

background:
  enable: false
  url: 'https://cdn.jsdelivr.net/gh/Tokisaki-Galaxy/res/site/medias/background.jpg'

artitalk:
  enable: false
  appId: # xxxxx
  appKey: # xxxxxx

bbtime:
  enable: false
  appId:
  appKey:
  serverURLs: # https://你的api

mermaid:
  enable: false # default false
  version: 'latest' # default v7.1.2
  options:
