# main menu navigation url and icon

menu:
  Index:
    url: /
    icon: fas fa-home
  Tags:
    url: /tags
    icon: fas fa-tags
  Categories:
    url: /categories
    icon: fas fa-bookmark
  Archives:
    url: /archives
    icon: fas fa-archive
  About:
    url: /about
    icon: fas fa-user-circle
  Contact:
    url: /contact
    icon: fas fa-comments
  Friends:
    url: /friends
    icon: fas fa-address-book
  
  #Medias:
  #  icon: fas fa-list
  #  children:
  #    - name: Musics
  #      url: /musics
  #      icon: fas fa-music
  #    - name: Movies
  #      url: /movies
  #      icon: fas fa-film
  #    - name: Books
  #      url: /books
  #      icon: fas fa-book
  #    - name: Galleries
  #      url: /galleries
  #      icon: fas fa-image

# Website start time.

time:
  enable: false
  year: 2019 # 
  month: 06 # 
  date: 28 # 
  hour: 00 # 
  minute: 00 # 
  second: 00 #


cover:
  showPrevNext: true 
  showIndicators: true 
  autoLoop: true
  duration: 120 
  intervalTime: 5000 
  useConfig: false 
  video:
    enable: false
    src: 
      - https://txmov2.a.yximgs.com/upic/2021/04/09/22/BMjAyMTA0MDkyMjMwMDhfMTg1ODk2MDg4N180NzUyOTMyMjA4Nl8xXzM=_b_B8e080d7ede19e6674d48a9f12545007b.mp4?pkey=AAVAfNhi5_f-HGkIPXrY5w6nyf4JibwOY-WwdHgSJ2aSoi-2WQLpiYDunLbRZQuESz875eMdsepRlVFtXg9nuQY58uRc-7AsF0kEMNR6QYBj56g9JFFMSGdsoKK2-SV27u8&tag=1-1617978682-xpcwebprofile-0-lcvipceuti-9e40072f87531f1a&clientCacheKey=3xbbtbrfxqpccp4_b.mp4
      - https://txmov2.a.yximgs.com/upic/2021/04/09/21/BMjAyMTA0MDkyMTQyNDRfMTg1ODk2MDg4N180NzUyNjAyMzA0N18xXzM=_b_B83b004b85aba8eca3ded270637616575.mp4
      - https://txmov2.a.yximgs.com/upic/2021/04/09/21/BMjAyMTA0MDkyMTU4MDNfMTg1ODk2MDg4N180NzUyNzE0MzkyNV8xXzM=_b_Bf94cee6bd181efeaca64049bd2e4e276.mp4
# index page dream text,

# index page dream text,

dream:
  enable: true
  showTitle: true
  title: sample Dream
  text: This is sample text

# Whether to display the musics.

music:
  enable: true
  title: #Non-bottom mode is valid
    enable: true
    show: Listen to music
  autoHide: true    
  server: netease   #require	music platform: netease, tencent, kugou, xiami, baidu
  type: playlist    
  id: 503838841     #require	song id / playlist id / album id / search keyword
  fixed: true       
  autoplay: false   
  theme: '#42b983'
  loop: 'all'      
  order: 'random'   
  preload: 'auto'   
  volume: 0.7       
  listFolded: true  
  hideLrc: true     

# Whether to display the musics.

musics:
  enable: false
  title:          
    enable: true
    show: Music
  server: tencent   
  type: playlist    
  id: 1776127550     
  fixed: false      
  autoplay: true   
  theme: '#42b983'
  loop: 'all'      
  order: 'random' 
  preload: 'auto'   
  volume: 0.7       
  listFolded: false  
  listMaxHeight: "525px" 


video:
  enable: false
  showTitle: true
  title: Video Title
  url: 
  iframeUrl: 
  pic:
  thumbnails:
  height: 
  autoplay: false 
  theme: '#42b983'
  loop: false 
  preload: 'auto' 
  volume: 0.7


recommend:
  enable: true
  showTitle: true
  useConfig: false 
 


favicon: /favicon.png
logo: /medias/logo.png



indexbtn:
  enable: true
  name: Github
  icon: fab fa-github-alt
  url: https://github.com/tm-LBenson



socialLink:
  github:  https://github.com/tm-LBenson
  email: tm-lewisbenson@gmail.com
  facebook: 
  twitter: 
  qq: 
  weibo: 
  zhihu: 
  rss: false 


toc:
  enable: true
  heading: h2, h3, h4
  collapseDepth: 0 
  showToggleBtn: true 


code:
  lang: true 
  copy: true 
  shrink: true 
  break: false 


reward:
  enable: true
  title: reward
  wechat: /medias/reward/wechat.png
  alipay: /medias/reward/alipay.jpg


copyright:
  enable: false
  minCharNumber: 120 
  description: copyright description

mathjax:
  enable: false
  cdn: https://cdn.bootcss.com/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML



postInfo:
  date: true 
  update: false
  wordCount: false 
  totalCount: false 
  min2read: false 
  readCount: false 


clicklove:
  enable: true

sakura:
  enable: false


mouseStar:
  enable: false


snowdown:
  enable: false

# profile in about page, including avatars, career, and personal introductions.

profile:
  avatar: /medias/avatar.jpg
  career: Software Engineer
  introduction: If you wish to succeed, you should use persistence as your good friend, experience as your reference, prudence as your brother and hope as your sentry.

# config my projects informations in about page.
# If you don't want to display this `My Projects` content, you can deactivate or delete this configuration.

myProjects:
  enable: true
  data:
    hexo-theme-matery:
      icon: fas fa-file-alt
      iconBackground: 'linear-gradient(to bottom right, #66BB6A 0%, #81C784 100%)'
      url: https://github.com/tm-LBenson
      desc: I will need to include a project here
    Fenix:
        icon: fas fa-database
        iconBackground: 'linear-gradient(to bottom right, #F06292 0%, #EF5350 100%)'
        url: https://github.com/tm-LBenson
        desc: I will need to include a project here
    typora-vue-theme:
        icon: fas fa-file-alt
        iconBackground: 'linear-gradient(to bottom right, #29B6F6 0%, #1E88E5 100%)'
        url: https://github.com/tm-LBenson
        desc: I will need to include a project here

# config my skills informations in about page.
# If you don't want to display this `My Skills` content, you can deactivate or delete this configuration.

mySkills:
  enable: true
  data:
    
    JavaScript:
      background: 'linear-gradient(to right, #9900FF 0%, #CC66FF 100%)'
      percent: 80%
    HTML5:
      background: 'linear-gradient(to right, #2196F3 0%, #42A5F5 100%)'
      percent: 80%
    CSS:
      background: 'linear-gradient(to right, #00BCD4 0%, #80DEEA 100%)'
      percent: 70%
    SQL:
      background: 'linear-gradient(to right, #4CAF50 0%, #81C784 100%)'
      percent: 90%
   

# config gallery of my photos in about page.
# If you don't want to display this `Gallery` content, you can deactivate or delete this configuration.

myGallery:
  enable: true
  data:
    - /medias/featureimages/0.jpg
    - /medias/featureimages/1.jpg
    - /medias/featureimages/2.jpg

# Whether to display post-calender in the `archive` page

postCalendar: true


gitalk:
  enable: false
  owner:
  repo:
  oauth:
    clientId:
    clientSecret:
  admin:


gitment:
  enable: false
  owner:
  repo:
  oauth:
    clientId:
    clientSecret:


disqus:
  enable: false
  shortname:


livere:
  enable: false
  uid:


tcaptcha:
  enable: true
  appid: xxxxxxxxxx # 你的appid

# The configuration of the Valine comment module is not activated by default.
# To use it, activate the configuration item and set appId and appKey.

valine:
  enable: false
  appId:  # 
  appKey: # 
  serverURLs: #
  notify: false
  verify: false
  visitor: true
  avatar: 'mm' # 
  pageSize: 10
  placeholder: 'just go go' # Comment Box placeholder
  background: /medias/comment_bg.png
  coolpushkey: 


waline:
  enable: false

  serverURL: https://waline.your-domain.com
  avatar: 'mp' 

changyan:
  enable: false
  appId:
  conf:


githubLink:
  enable: true
  url: https://github.com/tm-LBenson
  title: Check out my GitHub


twikoo:
  enable: false
  envId: twikoo-1gs9l0fb17e7897a 


verifyPassword:
  enable: false
  promptMessage: Password is required
  errorMessage: Incorrect password!


busuanziStatistics:
  enable: true
  totalTraffic: true 
  totalNumberOfvisitors: true 


googleAnalytics:
  enable: false
  id:



baiduAnalytics:
  enable: false
  id:


baiduPush: true


libs:
  css:
    matery: /css/matery.css
    mycss: /css/my.css
    post: /css/post.css
    reward: /css/reward.css
    dark: /css/dark.css
    indexcover: /css/indexcover.css
    gallery: /css/gallery.css
    fontAwesome: /libs/awesome/css/all.min.css # V6.1.2 20220809
    materialize: /libs/materialize/materialize.min.css # 1.0.0 20211109
    aos: /libs/aos/aos.css
    animate: /libs/animate/animate.min.css # V3.5.1
    lightgallery: /libs/lightGallery/css/lightgallery.min.css # V1.10.0
    aplayer: /libs/aplayer/APlayer.min.css
    dplayer: /libs/dplayer/DPlayer.min.css
    gitalk: /libs/gitalk/gitalk.css
    jqcloud: /libs/jqcloud/jqcloud.css
    tocbot: /libs/tocbot/tocbot.css
    prism: /libs/prism/prism.min.css
    mermaid: /libs/mermaid/mermaid.min.css
    fancybox: /libs/fancybox/jquery.fancybox.css
    justifiedGallery: /libs/justifiedGallery/justifiedGallery.min.css
  js:
    matery: /js/matery.js
    sc2tc: /js/tw_cn.js
    jquery: /libs/jquery/jquery-3.6.0.min.js  #3.6.0 20211109
    materialize: /libs/materialize/materialize.min.js # 1.0.0
    masonry: /libs/masonry/masonry.pkgd.min.js # v4.0.0
    aos: /libs/aos/aos.js
    scrollProgress: /libs/scrollprogress/scrollProgress.min.js
    lightgallery: /libs/lightGallery/js/lightgallery-all.min.js # V1.10.0
    typed: /libs/typed/typed.js
    clicklove: /libs/others/clicklove.js
    sakura: /libs/others/sakura.js
    star: /libs/others/star.js
    snow: /libs/others/snow.js
    tcaptcha: /libs/others/TencentCaptcha.js
    busuanzi: /libs/others/busuanzi.pure.mini.js
    aplayer: /libs/aplayer/APlayer.min.js
    meting: /libs/aplayer/Meting.min.js
    dplayer: /libs/dplayer/DPlayer.min.js
    crypto: /libs/cryptojs/crypto-js.min.js
    echarts: /libs/echarts/echarts.min.js
    gitalk: /libs/gitalk/gitalk.min.js
    valine: /libs/valine/Valine.min.js 
    minivaline: /libs/minivaline/MiniValine.js # latest
    waline: /libs/waline/Waline.min.js 
    twikoo: /libs/twikoo/twikoo.all.min.js 
    jqcloud: /libs/jqcloud/jqcloud-1.0.4.min.js
    tocbot: /libs/tocbot/tocbot.min.js
    canvas_nest: /libs/background/canvas-nest.js
    ribbon: /libs/background/ribbon.min.js
    ribbonRefresh: /libs/background/ribbon-refresh.min.js
    ribbon_dynamic: /libs/background/ribbon-dynamic.js
    instantpage: /libs/instantpage/instantpage.js
    mermaid: /libs/mermaid/mermaid.min.js
    fancybox: /libs/fancybox/fancybox.js
    justifiedGallery: /libs/justifiedGallery/justifiedGallery.min.js
    prism: /libs/prism/prism.min.js
    codeblock: /libs/codeBlock/codeBlockFuction.js
    codelang: /libs/codeBlock/codeLang.js
    codecopy: /libs/codeBlock/codeCopy.js
    codeshrink: /libs/codeBlock/codeShrink.js

# The post featured images that needs to be displayed when there is no image.

featureImages:
- /medias/featureimages/0.jpg
- /medias/featureimages/1.jpg
- /medias/featureimages/2.jpg
- /medias/featureimages/3.jpg
- /medias/featureimages/4.jpg
- /medias/featureimages/5.jpg
- /medias/featureimages/6.jpg
- /medias/featureimages/7.jpg
- /medias/featureimages/8.jpg
- /medias/featureimages/9.jpg
- /medias/featureimages/10.jpg
- /medias/featureimages/11.jpg
- /medias/featureimages/12.jpg
- /medias/featureimages/13.jpg
- /medias/featureimages/14.jpg
- /medias/featureimages/15.jpg
- /medias/featureimages/16.jpg
- /medias/featureimages/17.jpg
- /medias/featureimages/18.jpg
- /medias/featureimages/19.jpg
- /medias/featureimages/20.jpg
- /medias/featureimages/21.jpg
- /medias/featureimages/22.jpg
- /medias/featureimages/23.jpg


reprint:
  enable: true # whether enable reprint section 是否启用“转载规则限定模块”
  default: cc_by

# DaoVoice online contact
daovoice:
  enable: false
  app_id:

# Tidio online contact
tidio:
  enable: false
  public_key:

# 腾讯兔小巢，见https://txc.qq.com/
tuxiaochao:
  enable: false
  productId:
#背景canvas-nest
canvas_nest:
  enable: false
  color: 0,0,255 # 线条颜色, 默认: '0,0,0' ；三个数字分别为(R,G,B)，注意用,分割
  pointColor: 0,0,255 # 交点颜色, 默认: '0,0,0' ；三个数字分别为(R,G,B)，注意用,分割
  opacity: 0.7 # 线条透明度（0~1）, 默认: 0.5
  zIndex: -1 # 背景的 z-index 属性，css 属性用于控制所在层的位置, 默认: -1.
  count: 99 # 线条的总数量, 默认: 99

# 背景静止彩带.
ribbon:
  enable: false
  size: 150 # 彩带大小, 默认: 90.
  alpha: 0.6 # 彩带透明度 (0 ~ 1), 默认: 0.6.
  zIndex: -1 # 背景的z-index属性，css属性用于控制所在层的位置, 默认: -1.
  clickChange: false  # 设置是否每次点击都更换彩带.

# 背景动态彩带.
ribbon_dynamic:
  enable: false


sharejs:
  enable: true
  sites: twitter,facebook,google,qq,qzone,wechat,weibo,douban,linkedin

# addthis文章分享模块.
addthis:
  enable: false
  pubid:  # 前往https://www.addthis.com/获取

# 打字效果副标题.
# 如果有符号 ‘ ，请在 ’ 前面加上 \
subtitle:
  enable: true
  loop: true # 是否循环
  showCursor: true # 是否显示光标
  startDelay: 300 # 开始延迟
  typeSpeed: 100 # 打字速度
  backSpeed: 50 # 删除速度
  sub:
    - This is in the subtitle area
    - Never really desperate, only the lost of the soul

# 手机二级菜单.
navMenu:
  mleft: false # 二级侧栏子菜单是否对齐左边
  bgColor: " " # 二级侧栏子菜单背景颜色,留空即为全局背景色

# 网页预加载.
instantpage:
  enable: true

# banner 是否每日切换.
# 若为 false, 则 banner 默认为 /medias/banner/0.jpg
banner:
  enable: true

# 中文繁简转换开关
# 显示在底部 footer 栏
translate:
  enable: false

#ICP备案信息尾部显示
icp:
  enable: false
  url: # 备案链接
  text: # 备案信息


jsDelivr:
  url: 
  

background:
  enable: false
  url: "https://cdn.jsdelivr.net/gh/Tokisaki-Galaxy/res/site/medias/background.jpg"

# 说说 https://artitalk.js.org/
artitalk:
  enable: false
  appId: # xxxxx
  appKey: # xxxxxx


bbtime:
  enable: false
  appId: # 你的appId
  appKey: # 你的appKey
  serverURLs: # https://你的api



mermaid: 
  enable: false  # default false
  version: "latest" # default v7.1.2
  options:  